name: Scheduled Run

on:
  schedule:
    - cron: '20 17 * * *'  # Runs every day at 16:00 UTC, which is 00:00 in Asia/Shanghai timezone

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python pixiv.py

    - name: Commit and Push changes
      run: |
        git config --global user.name 'xunxun2001'
        git config --global user.email 'fhr2001@qq.com'
        git add README.md
        git commit -m "Update Repo with latest pixiv images" || echo "No changes to commit"
        git push --set-upstream https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/xunxun2001/pixiv-cron.git main
